extraction:
  cpp:
    prepare:
      packages:
        - libbsd-dev
        - libconfig++-dev
        - libsndfile1-dev
        - libspeex-dev
        - libsamplerate0-dev
    configure:
      command:
        - mkdir _lgtm_build_dir
        - cd _lgtm_build_dir
        - cmake -DBUILD_GTEST=OFF -DINSTALL_GTEST=OFF ..
    index:
      build_command:
        - cd _lgtm_build_dir
        - make
