language: cpp

dist: focal

before_install:
  - sudo apt-get -y install libiniparser-dev libsndfile1-dev libspeex-dev

compiler:
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
