name: Coderrect Scan

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
    
    - name: Get commit hash
      run: git rev-parse HEAD

    # Runs a set of commands using the runners shell
    - name: Build
      run: |
        mkdir -p build
        cd build
        cmake ..
        make
    
    - name: Coderrect Scan
      uses: BradSwain/coderrect-github-action@main
      with:
        buildPath: "build"
